source "https://api-dev.allianz.de/ghe/AMOS-TH-Mobile/iOS-Library-CocoaPods-Specs.git"
source "https://github.com/CocoaPods/Specs.git"

use_frameworks!
platform :ios, '9.0'

target 'PoringKit_Example' do
  pod 'PoringKit', :path => '../'
  pod 'SwiftLint'
  
  target 'PoringKit_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
