use_frameworks!
platform :ios, '9.0'

target 'PoringKit_Example' do
  pod 'PoringKit', :path => '../'
  pod 'SwiftLint'
end

target 'PoringKit_Tests' do
  pod 'PoringKit', :path => '../'
  
  pod 'Quick'
  pod 'Nimble'
end
